FROM php:7.4-fpm

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    libzip-dev zip \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip pdo pdo_mysql

COPY . .

RUN composer install

EXPOSE 9000

CMD ["php-fpm"]
